<div id="navegacion" prev="../Ejercicios_Tema_6/uso_numpy.html" next=""></div>

<div class="section-title">Sección 3.7</div>

# Ejercicios

Los enlaces que te encuentres en esta página, solo funcionan desde el formato html, no desde el notebook una vez descargado.

## Ejercicio 1

El fichero [rotterdam_rainfall.txt](./datos/rotterdam_rainfall.txt) recoge los datos de las precipitaciones diarias de la estación meteorológica de Rotterdam en 2012.

* La primera columna representa la fecha.
* La segunda columna representa la cantidad de precipitaciones expresado en 0.1 mm (-1 si es menor a 0.05 mm).
* El separador de campos es el caracter `, `.

__a)__ Crear un array de `numpy` con los datos del fichero [rotterdam_rainfall.txt](./datos/rotterdam_rainfall.txt). El array ha de llamarse `precipitaciones`.

   * Descarga el fichero  en tu directorio de trabajo.
   * Carga el fichero mediante la función `loadtxt`. Usa el parámetro  `delimiter` con valor `,`. Usa el parámetro `dtype` para indicar que los valores sean de tipo `int`.

In [ ]:
# Sol
import numpy as np
precipitaciones = np.loadtxt('/content/rotterdam_rainfall.txt', delimiter=',', dtype=int)
precipitaciones

array([[20120101,      207],
       [20120102,       -1],
       [20120103,      144],
       [20120104,       36],
       [20120105,       84],
       [20120106,        8],
       [20120107,       30],
       [20120108,       -1],
       [20120109,        8],
       [20120110,        0],
       [20120111,       10],
       [20120112,        9],
       [20120113,        4],
       [20120114,       -1],
       [20120115,        0],
       [20120116,        0],
       [20120117,        0],
       [20120118,       32],
       [20120119,      144],
       [20120120,       -1],
       [20120121,       35],
       [20120122,       19],
       [20120123,       16],
       [20120124,        5],
       [20120125,        5],
       [20120126,       33],
       [20120127,       -1],
       [20120128,       -1],
       [20120129,        0],
       [20120130,        1],
       [20120131,       -1],
       [20120201,        0],
       [20120202,        0],
       [20120203,       27],
       [201202

__b)__ Averigua el número de días donde la cantidad de precipitaciones es mayor a 0.05 mm (valor mayor que -1).
    
* Primero crea un filtro donde la cantidad de precipitaciones (columna 1) sea mayor que  -1.
* Aplica el filtro al array `precipitaciones`. Guarda el resultado en un nuevo array llamado `precip_positivas`.
* Puedes usar la función `len` para calcular el tamaño del array  `precip_positivas`.

In [ ]:
# Sol: 324 días
precip_positivas = precipitaciones[precipitaciones[:,1] > -1]   #Forma de coger la segunda col
len(precip_positivas)

324


__c)__ Calcula el valor medio de la cantidad de precipitación. No tengas en cuenta las precipitaciones con valor -1, por tanto usa el array `precip_positivas` para calcular dicho valor medio.

   * Utiliza la función `mean`.
    


In [ ]:
# Sol: 30.700617283950617
precip_positivas[:,1].mean()


30.700617283950617

__d)__ Calcula el día que ha tenido mayor cantidad de precipitación y la cantidad de precipitación.

   * Utiliza las funciones `argmax` y `max`.

In [ ]:
# Sol: Máxima precipitación: 224.
#      Día de máxima precipitación : 20121222
# print(precip_positivas[:,1].max()) #tambien sirve
maximo = np.argmax(precip_positivas[:,1])
print(precip_positivas[maximo, 1])
precip_positivas.max()



224


20121231

__e)__ Expresa la cantidad de precipitación en mm. Para ello multiplica la cantidad de precipitación por 10.

   

In [ ]:
# Sol: Los primeros valores del resultado son:

#    array([[20120101,     2070],
#           [20120102,      -10],
#           [20120103,     1440],
#           [20120104,      360],
#            ...
#            ...
array = precipitaciones[:] * 10
array

array([[201201010,      2070],
       [201201020,       -10],
       [201201030,      1440],
       [201201040,       360],
       [201201050,       840],
       [201201060,        80],
       [201201070,       300],
       [201201080,       -10],
       [201201090,        80],
       [201201100,         0],
       [201201110,       100],
       [201201120,        90],
       [201201130,        40],
       [201201140,       -10],
       [201201150,         0],
       [201201160,         0],
       [201201170,         0],
       [201201180,       320],
       [201201190,      1440],
       [201201200,       -10],
       [201201210,       350],
       [201201220,       190],
       [201201230,       160],
       [201201240,        50],
       [201201250,        50],
       [201201260,       330],
       [201201270,       -10],
       [201201280,       -10],
       [201201290,         0],
       [201201300,        10],
       [201201310,       -10],
       [201202010,         0],
       [

## Ejercicio 2

Dos niños están haciendo una colección de cromos. Cada cromo tiene asignado un número entero entre 1 y 200.

* Los cromos que tiene Juan se encuentran en el fichero [juan.txt](./datos/col_juan.txt). La primera columna representa el número asociado al cromo y la segunda columna representa el número de cromos con ese número que tiene Juan.

* Los cromos que tiene Pedro se encuentran en el fichero [pedro.txt](./datos/col_pedro.txt). La primera columna representa el número asociado al cromo y la segunda columna representa el número de cromos con ese número que tiene Pedro.

__a)__ Crear un array de `numpy` con los datos de cada una de las colecciones. Los arrays han de llamarse `juan`y `pedro`.

   * Descarga los ficheros  en tu directorio de trabajo.
   * Carga cada uno de los ficheros mediante la función `loadtxt`. Usa el parámetro  `delimiter` con valor `,`. Usa el parámetro `dtype` para indicar que los valores sean de tipo `int`.

In [ ]:
# Sol:
juan = np.loadtxt('/content/col_juan.txt', delimiter=',', dtype=int)
pedro = np.loadtxt('/content/col_pedro.txt', delimiter=',', dtype=int)

<ipython-input-9-0fd99e4ad8ea>:2: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  juan = np.loadtxt('/content/col_juan.txt', delimiter=',', dtype=int)
<ipython-input-9-0fd99e4ad8ea>:3: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (O

__b)__ Calcula el número de cromos diferentes que tiene cada niño.

In [ ]:
# SOl:
# juan tiene 68 cromos
# pedro tiene 124 cromos
print('juan tiene', len(juan), 'cromos')
print('pedro tiene', len(pedro), 'cromos')

juan tiene 68 cromos
pedro tiene 124 cromos


__c)__ Calcula el número de cromos totales que tiene cada niño (contando los cromos repetidos).

In [ ]:
# SOl:
# pedro tiene 1326 cromos
# juan tiene 619 cromos
print('pedro tiene', pedro[:,1].sum(), 'cromos')
print('juan tiene', juan[:,1].sum(), 'cromos')

pedro tiene 1326 cromos
juan tiene 619 cromos


__d)__ Calcula el número de cromos que aparecen en las dos colecciones. Puedes usar la función `np.intersect1d`.

In [ ]:
# Sol
# Hay 44 cromos que aparecen en las dos colecciones
print('Hay', len(np.intersect1d(juan[:,0], pedro[:,0])), 'cromos que aparecen en las dos colecciones')

Hay 44 cromos que aparecen en las dos colecciones


__e)__ Entre los dos niños, ¿forman la colección completa?. Puedes usar la función `np.union1d`.

In [ ]:
# Sol:
# No Forman la colección completa. Entre los dos, solo tienen 148 cromos distintos y la colección tiene 200 cromos

coleccion_completa = 200

union_cromos = np.union1d(juan[:,0], pedro[:,0])
num_cromos = len(union_cromos)

if np.array_equal(num_cromos, coleccion_completa):
  print('Forman una colección completa')
else:
  print('No Forman la colección completa. Entre los dos, solo tienen', num_cromos, 'cromos distintos y la colección tiene 200 cromos')

No Forman la colección completa. Entre los dos, solo tienen 148 cromos distintos y la colección tiene 200 cromos


__f)__ ¿Qué números faltan para tener la colección completa?

* Puedes generar un array de todos los cromos de la colección con la función `arange`.
* Usa la función `np.in1d`

In [ ]:
# Sol:
# Listado de los cromos que faltan:
#      [  1,   3,  12,  16,  17,  21,  30,  34,  38,  45,  46,  48,  52,
#        55,  66,  69,  72,  75,  76,  81,  82,  91,  92,  96, 100, 106,
#       107, 113, 114, 119, 122, 124, 125, 129, 138, 139, 140, 146, 151,
#       154, 155, 173, 176, 180, 181, 184, 185, 186, 190, 194, 199, 200]

coleccion_completa = np.arange(1, 201)

coleccion_completa[~np.in1d(coleccion_completa, union_cromos)]

array([  1,   3,  12,  16,  17,  21,  30,  34,  38,  45,  46,  48,  52,
        55,  66,  69,  72,  75,  76,  81,  82,  91,  92,  96, 100, 106,
       107, 113, 114, 119, 122, 124, 125, 129, 138, 139, 140, 146, 151,
       154, 155, 173, 176, 180, 181, 184, 185, 186, 190, 194, 199, 200])

---------------------